name: CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest -vvv

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install flake8
        run: pip install flake8

      - name: Lint code
        run: flake8 . --exclude venv --max-line-length 106

  compare-versions:
    name: Check Image Version Incremented
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Version
        run: |
          # Fetch the current version from the VERSION file
          current_version=$(cat VERSION)

          # Fetch the previous semantic version (excluding 'latest') from Docker images
          previous_version=$(docker image ls --filter "reference=${{ secrets.DOCKER_USERNAME }}/csv-merger" --format "{{.Repository}}:{{.Tag}}" | awk -F ':' '{print $2}' | grep -v 'latest' | sort -rV | head -n 1)

          # Function to compare semantic versions
          version_greater() {
              IFS='.' read -r -a current_parts <<< "$1"
              IFS='.' read -r -a previous_parts <<< "$2"

              for ((i=0; i<${#current_parts[@]}; i++)); do
                  if [[ ${current_parts[$i]} -gt ${previous_parts[$i]} ]]; then
                      return 0
                  elif [[ ${current_parts[$i]} -lt ${previous_parts[$i]} ]]; then
                      return 1
                  fi
              done

              return 1
          }

          # Compare the current and previous versions
          if version_greater "$current_version" "$previous_version"; then
              echo "The version has been properly incremented: $previous_version -> $current_version"
          else
              echo "Error: The version has not been incremented properly: $previous_version -> $current_version"
              exit 1
          fi

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [run-tests, lint, compare-versions]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          current_version=$(cat VERSION)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/csv-merger:$current_version -t ${{ secrets.DOCKER_USERNAME }}/csv-merger:latest .
          docker save --output csv-merger.docker ${{ secrets.DOCKER_USERNAME }}/csv-merger:$current_version
          docker save --output csv-merger-latest.docker ${{ secrets.DOCKER_USERNAME }}/csv-merger:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            csv-merger.docker
            csv-merger-latest.docker

  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker load --input ./csv-merger.docker
          docker load --input ./csv-merger-latest.docker
          current_version=$(cat VERSION)
          docker push ${{ secrets.DOCKER_USERNAME }}/csv-merger:$current_version
          docker push ${{ secrets.DOCKER_USERNAME }}/csv-merger:latest

  deploy-docker-compose:
    name: Deploy Docker Compose
    runs-on: ubuntu-latest
    needs: [build-docker-image, push-docker-image]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure SSH key is available
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SSH connection
        run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'echo "SSH connection successful"'

      - name: Copy Docker Compose file to remote server
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hostsz
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/csv-merger-api/docker-compose.yml
